---
- hosts: all
  become: True
  tasks:
    - name: Install packages
      apt:
        name: "apache2"
        state: "present"
    - name: Start apache2 server
      service:
        name: apache2
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html # We have define a html page
        dest: /var/www/html/
...
