---
 - name: Run the test playbook
   gather_facts: false
   hosts: all
   tasks:
      - name: Get the username running this playbook
        become: false
        local_action: command whoami
        register: username_on_the_host

      - name: display ur name
        debug:
           msg: "Hello user {{ username_on_the_host.stdout }} from Jenkins and Ansible!!"
...
